site_name: Manual NP³ MS Workflow
site_description: The documentation of the NP³ MS Workflow commands and usage.
site_author: Cristina F Bazzano

# Repository
repo_url: https://github.com/danielatrivella/NP3_MS_Workflow
repo_name: NP3_MS_Workflow
#edit_uri: edit/master/docs/

# Copyright
copyright: Copyright &copy; 2020 - 2020 CNPEM LNBIO

# Configuração do Tema Material
theme:
  name: material
  language: en               # Traduz elementos da interface para ingles
  logo: img/logo_np3ms.png
  favicon: img/logo_np3ms.png
  features:
    - navigation.tabs        # Menu superior para grandes seções (opcional)
    - navigation.sections    # Agrupa tópicos no menu lateral
    - navigation.expand      # Deixa os menus lateral abertos por padrão
    - search.suggest         # Sugestões de busca ao digitar
    - search.highlight       # Destaca o texto buscado nas páginas
    - header.autohide
    - content.footnote.tooltips
    - content.code.copy  # This enables the copy button globally
  palette:
    # Configuração de cor (Modo Claro)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: blue-gray
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo escuro
    # Configuração de cor (Modo Escuro)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: blue-gray
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro
  icon:
    repo: fontawesome/brands/git-alt
  font:
    text: Roboto
    code: Roboto Mono

# enable footnotes
markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.highlight:  # enable code copy
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite

# ---- ADICIONE OS LINKS no rodape ----
extra:
  social:
    - icon: material/web             # Ícone de Website mundial
      link: https://lnbio.cnpem.br/divisoes-cientificas/descoberta-de-farmacos/  # Substitua pelo link real do NP3
      name: Visit CNPEM-LNBio Drug Discovery Division

# Menu de Navegação (Mapeamento dos seus tópicos)
nav:
  - Overview:
      - Introduction: pages/overview/index.md
      - Commands: pages/overview/index_cmds.md
      - Data Input and Output: pages/overview/index_data.md
  - Installation and Setup:
      - Installation: pages/installation_setup/installation.md
      - Setup: pages/installation_setup/setup.md
  - Metadata:
      - Metadata Creation: pages/01_metadata/description.md
  - Run:
      - Description: pages/cmd_run/description.md
      - Final Reports: pages/cmd_run/final_reports.md
  - Pre_process:
      - Description: pages/02_pre_process/description.md
      - Details: pages/02_pre_process/details.md
      - Optimization: pages/02_pre_process/optimization.md
  - Clustering:
      - Description: pages/03_clustering/description.md
      - Details: pages/03_clustering/details.md

